[WIP]readme
keita-n1/chat-space pull request #2
Opened 2019-05-05 09:21 UTC by keita-n1

#WHAT
テーブルを洗い出した

#WHY
サービスに必須なため

2019-05-05 09:24 UTC, yuki-uchida requested changes

2019-05-05 09:24 UTC, yuki-uchida commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
外部キー制約をつけたい場合にはrefferences型としましょう

2019-05-05 09:24 UTC, yuki-uchida commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
このカラムは間違っています。
どのテーブルとどのテーブルがどのような関係で結びついているのか、ER図を書くことで確認して見ましょう

2019-05-07 06:47 UTC, keita-n1 commented
修正完了しました。

2019-05-07 06:50 UTC, TOMARUMARU commented on README.md
> +|body|text|add_index :messages, :body, null: false|
indexもnull: falseも不要です

2019-05-07 06:50 UTC, TOMARUMARU commented on README.md
> +|group_name|string|add_index :groups, :group_name, null: false|
nameで大丈夫です

2019-05-07 06:50 UTC, TOMARUMARU commented on README.md
> +|member|string|null: false|
何用のカラムでしょうか？

2019-05-07 06:51 UTC, TOMARUMARU commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
修正されてません

2019-05-07 06:55 UTC, keita-n1 commented on README.md
> +|member|string|null: false|
memberカラムはいらないってことでしょうか？

2019-05-07 07:05 UTC, keita-n1 commented
再修正致しました。

2019-05-07 07:07 UTC, miyagit approved these changes
LGTMです。

2019-05-07 07:12 UTC, merged